version: '3.9'
services:
  app:
    depends_on:
      - api
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - 1111:80
    environment:
      - BACKEND_HOST=http://api:80
    networks:
      - backend
  api:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - 3333:80
    networks:
      - backend

networks:
  backend:
    driver: bridge
