version: '3.10'

services:
  jupyterlab:
    build:
      context: .
      dockerfile:  Dockerfile
    user: root
    environment:
      JUPYTER_TOKEN: "easy"
      CHOWN_HOME_OPTS: "-R"
      CHOWN_HOME: yes
      CHOWN_EXTRA: "/home/leo/work/notes"
    ports:
      - 8888:8888
    volumes:
      - .:/home/leo/work
      - ./notes:/home/leo/work/notes
