repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      exclude: ^src/containers
    - id: check-json
      exclude: ^src/.*tsconfig.json

- repo: http://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
        - --args=-write=true
