FROM osrf/ros:noetic-desktop-full

SHELL [ "/bin/bash", "-c" ]

ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install wget git python3-pip python3-catkin-tools -y
RUN apt-get install ros-noetic-joy ros-noetic-control-toolbox \
    ros-noetic-robot-controllers ros-noetic-gazebo-ros \
    ros-noetic-gmapping ros-noetic-robot-state-publisher \
    ros-noetic-rviz ros-noetic-gazebo-ros-control \
    ros-noetic-gazebo-ros-pkgs \
    # ros-noetic-ignition-math6-vendor \
    # ignition ignition-launch-cli ignition-tools \
    ros-noetic-gazebo-plugins ros-noetic-rgbd-launch -y
RUN apt-get install build-essential -y
WORKDIR /
RUN mkdir -p catkin_ws/src/
WORKDIR /catkin_ws/src/
RUN git clone https://github.com/ROBOTIS-GIT/turtlebot3_msgs.git
RUN git clone -b noetic-devel https://github.com/ROBOTIS-GIT/turtlebot3.git
RUN git clone https://github.com/ROBOTIS-GIT/turtlebot3_simulations.git
RUN echo "export TURTLEBOT3_MODEL=burger" > ~/.bashrc
RUN echo "source /opt/ros/noetic/setup.bash" > ~/.bashrc
RUN echo "source /catkin_ws/devel/setup.bash" > ~/.bashrc
RUN pip3 install rospkg

RUN source /opt/ros/noetic/setup.bash && \
    cd /catkin_ws/ && \
    catkin_init_workspace
# WORKDIR /opt/ros/noetic
# RUN . setup.bash
# WORKDIR /catkin_ws
# RUN catkin_make
WORKDIR /
COPY ./run_gazebo.sh ./run_rviz.sh ./run_algo.sh /
