version: "3.9"
networks:
  net:
    driver: bridge
services:
  api:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - 4000:80
    volumes:
      - "./backend/main.py:/app/main.py"
    networks:
      - net

  api-express:
    build:
      context: "./backend-express"
      dockerfile: Dockerfile
    ports:
      - 4001:3001
    volumes:
      - "./backend-express/src:/app/src"
    networks:
      - net

#   app:
#     build:
#       context: "./frontend"
#       dockerfile: Dockerfile
#     ports:
#       - 5000:80
#     volumes:
#       - "./frontend/:/app/"
#     environment:
#       - BACKEND_HOST=http://api:80
#     networks:
#       - net
