version: "3.9"
services:
  api:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - 4000:80
    volumes:
      - "./backend/main.py:/app/main.py"
#       - "./backend/requirements.txt:/app/requirements.txt"
#     networks:
#       - net

#   app:
#     build:
#       context: "./frontend"
#       dockerfile: Dockerfile
#     ports:
#       - 5000:80
#     volumes:
#       - "./frontend/:/app/"
#     environment:
#       - BACKEND_HOST=http://api:80
#     networks:
#       - net

# networks:
#   net:
#     driver: bridge
