apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: {{ .Values.app.image }}
        name: ubuntu
        command: ["/bin/sh", "-c"]
        args: 
          - apt-get update;
            apt-get -y install openssh-server;
            useradd leo;
            echo "leo:leo" | chpasswd;
            service ssh restart;
            sleep infinity;
        resources: {}
status: {}
