apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.route.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.name }}
  ports:
    - port: 22
      targetPort: 22
      nodePort: {{ .Values.route.nodePort }}
