import NavBar from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata = {
  title: "Drugig",
  description: "Generated by Drugig",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class">
          <NavBar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
