import NavBar from "@/components/navbar";
import "./globals.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen grid place-content-center">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
