networks:
  net:
    driver: bridge
services:
  neo4j:
    image: neo4j:latest
    container_name: "neo-gds1.5"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - apoc.import.file.enabled=true
      # - NEO4J_dbms_memory_pagecache_size=4G
      # - NEO4j_dbms_memory_heap_initial__size=4G
      # - NEO4J_dbms_memory_heap_max__size=8G
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - net
  add-data:
    build:
      context: .
      dockerfile: backend/Dockerfile.etl
      args:
        - HOSTNAME=neo4j
    entrypoint: python -m backend
    depends_on:
      - neo4j
    networks:
      - net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 10s
