apiVersion: v1
kind: ResourceQuota
metadata:
    name: compute-quota
    namespace: {{ .Values.namespace.name }}

spec:
    hard:
        pods: "10"
        requests.cpu: "1"
        requests.memory: 1Gi
        limits.cpu: "4"
        limits.memory: 4Gi
