apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace.name }}
data:
  DB_HOST: {{ .Values.secrets.host }}
  DB_USER: {{ .Values.secrets.user }}
  DB_PASSWORD: {{ .Values.secrets.pwd }}
