"""add post table

Revision ID: 695ce1267b3c
Revises: 99ee1cc3f26e
Create Date: 2024-03-16 23:55:08.630319

"""
from typing import Sequence, Union

import simple_auth
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '695ce1267b3c'
down_revision: Union[str, None] = '99ee1cc3f26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('posts')
    # ### end Alembic commands ###
