"""init user table

Revision ID: 99ee1cc3f26e
Revises:
Create Date: 2024-03-07 23:58:33.450896

"""
from typing import Sequence, Union

import simple_auth
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '99ee1cc3f26e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_pwd', sa.String(length=128), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
