name: Terraform CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        terraform-version: ["1.3.0"]
        os:
          - ubuntu-22.04
          # - macos-latest
          # - windows-latest
        path:
          - src/tf/batch-lambda
          - src/tf/aurora-postgres-rds
          - src/tf/cognito-app/infrastructure

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform-version }}

      - name: Terraform init
        working-directory: ${{ matrix.path }}
        id: init
        run: terraform init

      - name: Terraform format
        working-directory: ${{ matrix.path }}
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: ${{ matrix.path }}
        id: validate
        run: terraform validate

      # - name: Terraform plan
      #   working-directory: ${{ matrix.path }}
      #   id: plan
      #   run: terraform plan
