apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  containers:
  - image: {{ .Values.imageName }}
    name: {{ .Values.appName }}
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
