apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: {{ .Values.namespace.name }}
  labels:
    run: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  containers:
  - image: {{ .Values.imageName }}
    name: {{ .Values.appName }}
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "4Gi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
